// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLbXIe6Gt3z99bYRvnb5kTUUuNpQoHmVk',
    appId: '1:1020094490435:web:3f0b4ef654ec381ecfb1f6',
    messagingSenderId: '1020094490435',
    projectId: 'khaled-9ecc5',
    authDomain: 'khaled-9ecc5.firebaseapp.com',
    storageBucket: 'khaled-9ecc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqpkvVn2pm5lcgo-1pP1rpmkD5dVzoSps',
    appId: '1:1020094490435:android:63961a4ec3ff7762cfb1f6',
    messagingSenderId: '1020094490435',
    projectId: 'khaled-9ecc5',
    storageBucket: 'khaled-9ecc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_KcvtHIBf0og9SWNRGiDYSXdFByo1M-I',
    appId: '1:1020094490435:ios:4bb43b98279c09b4cfb1f6',
    messagingSenderId: '1020094490435',
    projectId: 'khaled-9ecc5',
    storageBucket: 'khaled-9ecc5.appspot.com',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_KcvtHIBf0og9SWNRGiDYSXdFByo1M-I',
    appId: '1:1020094490435:ios:8719d19110b46f3bcfb1f6',
    messagingSenderId: '1020094490435',
    projectId: 'khaled-9ecc5',
    storageBucket: 'khaled-9ecc5.appspot.com',
    iosBundleId: 'com.example.quran.RunnerTests',
  );
}
