// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJj6KcIcbYV-RZc9i5GAj1HcpsOSALZKo',
    appId: '1:352433770948:web:76f0dcac3b81dcac499491',
    messagingSenderId: '352433770948',
    projectId: 'quran-978e9',
    authDomain: 'quran-978e9.firebaseapp.com',
    storageBucket: 'quran-978e9.appspot.com',
    measurementId: 'G-Q43XV9DY8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwmefaRTm17iLAd3d6SKiiVhzWjZss_Ao',
    appId: '1:352433770948:android:548cd3462c63e407499491',
    messagingSenderId: '352433770948',
    projectId: 'quran-978e9',
    storageBucket: 'quran-978e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyoqnPnXrjW5NfWCfI_HB8I6r230uwZHI',
    appId: '1:352433770948:ios:f8f8677f3b064281499491',
    messagingSenderId: '352433770948',
    projectId: 'quran-978e9',
    storageBucket: 'quran-978e9.appspot.com',
    androidClientId: '352433770948-dlos2la0labf65v9ofn78j6h43ut993g.apps.googleusercontent.com',
    iosBundleId: 'com.efadh.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyoqnPnXrjW5NfWCfI_HB8I6r230uwZHI',
    appId: '1:352433770948:ios:873d459c0423baec499491',
    messagingSenderId: '352433770948',
    projectId: 'quran-978e9',
    storageBucket: 'quran-978e9.appspot.com',
    androidClientId: '352433770948-dlos2la0labf65v9ofn78j6h43ut993g.apps.googleusercontent.com',
    iosBundleId: 'com.efadh.quran.RunnerTests',
  );
}
